Organizations:

  - &OrdererOrg
      Name: OrdererOrg

      ID: OrdererMSP

      MSPDir: crypto-config/ordererOrganizations/hientang.com/msp

      Policies:
        Readers:
          Type: Signature
          Rule: "OR('OrdererMSP.member')"
        Writers:
          Type: Signature
          Rule: "OR('OrdererMSP.member')"
        Admins:
          Type: Signature
          Rule: "OR('OrdererMSP.admin')"

  - &Bachmai
      Name: BachmaiMSP

      ID: BachmaiMSP

      MSPDir: crypto-config/peerOrganizations/bachmai.hientang.com/msp

      Policies:
        Readers:
          Type: Signature
          Rule: "OR('BachmaiMSP.admin', 'BachmaiMSP.peer', 'BachmaiMSP.client')"
        Writers:
          Type: Signature
          Rule: "OR('BachmaiMSP.admin', 'BachmaiMSP.client')"
        Admins:
          Type: Signature
          Rule: "OR('BachmaiMSP.admin')"

      AnchorPeers:
        - Host: peer0.bachmai.hientang.com
          Port: 7051

  - &Choray
      Name: ChorayMSP

      ID: ChorayMSP

      MSPDir: crypto-config/peerOrganizations/choray.hientang.com/msp

      Policies:
        Readers:
          Type: Signature
          Rule: "OR('ChorayMSP.admin', 'ChorayMSP.peer', 'ChorayMSP.client')"
        Writers:
          Type: Signature
          Rule: "OR('ChorayMSP.admin', 'ChorayMSP.client')"
        Admins:
          Type: Signature
          Rule: "OR('ChorayMSP.admin')"

      AnchorPeers:
        - Host: peer0.choray.hientang.com
          Port: 7051

Capabilities:
  Channel: &ChannelCapabilities
    V1_3: true

  Orderer: &OrdererCapabilities
    V1_1: true

  Application: &ApplicationCapabilities
    V1_3: true
    V1_2: false
    V1_1: false


Application: &ApplicationDefaults

  Organizations:

  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"

  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults

  OrdererType: solo

  Addresses:
    - orderer.hientang.com:7050

  BatchTimeout: 2s

  BatchSize:

    MaxMessageCount: 10

    AbsoluteMaxBytes: 99 MB

    PreferredMaxBytes: 512 KB

  Organizations:

  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"

Channel: &ChannelDefaults
  Policies:
    # Who may invoke the 'Deliver' API
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    # Who may invoke the 'Broadcast' API
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    # By default, who may modify elements at this config level
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"

  Capabilities:
    <<: *ChannelCapabilities

Profiles:

  TwoOrgsOrdererGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Consortiums:
      SampleConsortium:
        Organizations:
          - *Bachmai
          - *Choray
  TwoOrgsChannel:
    Consortium: SampleConsortium
    <<: *ChannelDefaults
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Bachmai
        - *Choray
      Capabilities:
        <<: *ApplicationCapabilities
