OrdererOrgs:
  - Name: Orderer
    Domain: hientang.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Bachmai
    Domain: bachmai.hientang.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Choray
    Domain: choray.hientang.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
