OrdererOrgs:
  - Name: Orderer
    Domain: hientang.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
      - Hostname: orderer2
      - Hostname: orderer3
      - Hostname: orderer4
      - Hostname: orderer5
PeerOrgs:
  - Name: Bachmai
    Domain: bachmai.hientang.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Choray
    Domain: choray.hientang.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
