# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  hientang:

services:
  ca.bachmai.hientang.com:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.bachmai.hientang.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.bachmai.hientang.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${CERTIFICATE_BACHMAI_PRIVATE_KEY}
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - '7054:7054'
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.bachmai.hientang.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/${CERTIFICATE_BACHMAI_PRIVATE_KEY} -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/bachmai.hientang.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.bachmai.hientang.com
    networks:
      - hientang

  ca.choray.hientang.com:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.choray.hientang.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.choray.hientang.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${CERTIFICATE_CHORAY_PRIVATE_KEY}
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - '8054:8054'
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.choray.hientang.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/${CERTIFICATE_CHORAY_PRIVATE_KEY} -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/choray.hientang.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.choray.hientang.com
    networks:
      - hientang
