# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.hientang.com:
  peer0.bachmai.hientang.com:
  peer1.bachmai.hientang.com:
  peer0.choray.hientang.com:
  peer1.choray.hientang.com:

networks:
  hientang:

services:
  orderer.hientang.com:
    extends:
      file: base/docker-compose-base.yaml
      service: orderer.hientang.com
    container_name: orderer.hientang.com
    networks:
      - hientang

  peer0.bachmai.hientang.com:
    container_name: peer0.bachmai.hientang.com
    extends:
      file: base/docker-compose-base.yaml
      service: peer0.bachmai.hientang.com
    networks:
      - hientang

  peer1.bachmai.hientang.com:
    container_name: peer1.bachmai.hientang.com
    extends:
      file: base/docker-compose-base.yaml
      service: peer1.bachmai.hientang.com
    networks:
      - hientang

  peer0.choray.hientang.com:
    container_name: peer0.choray.hientang.com
    extends:
      file: base/docker-compose-base.yaml
      service: peer0.choray.hientang.com
    networks:
      - hientang

  peer1.choray.hientang.com:
    container_name: peer1.choray.hientang.com
    extends:
      file: base/docker-compose-base.yaml
      service: peer1.choray.hientang.com
    networks:
      - hientang

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.bachmai.hientang.com:7051
      - CORE_PEER_LOCALMSPID=BachmaiMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/bachmai.hientang.com/peers/peer0.bachmai.hientang.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/bachmai.hientang.com/peers/peer0.bachmai.hientang.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/bachmai.hientang.com/peers/peer0.bachmai.hientang.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/bachmai.hientang.com/users/Admin@bachmai.hientang.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./chaincode/:/opt/gopath/src/github.com/chaincode
      - $GOPATH/src/github.com/hyperledger:/opt/gopath/src/github.com/hyperledger
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.hientang.com
      - peer0.bachmai.hientang.com
      - peer1.bachmai.hientang.com
      - peer0.choray.hientang.com
      - peer1.choray.hientang.com
    networks:
      - hientang
