# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  orderer.hientang.com:
    container_name: orderer.hientang.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
      - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../crypto-config/ordererOrganizations/hientang.com/orderers/orderer.hientang.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/hientang.com/orderers/orderer.hientang.com/tls/:/var/hyperledger/orderer/tls
      - orderer.hientang.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.bachmai.hientang.com:
    container_name: peer0.bachmai.hientang.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.bachmai.hientang.com
      - CORE_PEER_ADDRESS=peer0.bachmai.hientang.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.bachmai.hientang.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.bachmai.hientang.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.bachmai.hientang.com:7051
      - CORE_PEER_LOCALMSPID=BachmaiMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/bachmai.hientang.com/peers/peer0.bachmai.hientang.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/bachmai.hientang.com/peers/peer0.bachmai.hientang.com/tls:/etc/hyperledger/fabric/tls
      - peer0.bachmai.hientang.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer1.bachmai.hientang.com:
    container_name: peer1.bachmai.hientang.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.bachmai.hientang.com
      - CORE_PEER_ADDRESS=peer1.bachmai.hientang.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.bachmai.hientang.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.bachmai.hientang.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.bachmai.hientang.com:7051
      - CORE_PEER_LOCALMSPID=BachmaiMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/bachmai.hientang.com/peers/peer1.bachmai.hientang.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/bachmai.hientang.com/peers/peer1.bachmai.hientang.com/tls:/etc/hyperledger/fabric/tls
      - peer1.bachmai.hientang.com:/var/hyperledger/production

    ports:
      - 8051:8051

  peer0.choray.hientang.com:
    container_name: peer0.choray.hientang.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.choray.hientang.com
      - CORE_PEER_ADDRESS=peer0.choray.hientang.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.choray.hientang.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.choray.hientang.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.choray.hientang.com:10051
      - CORE_PEER_LOCALMSPID=ChorayMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/choray.hientang.com/peers/peer0.choray.hientang.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/choray.hientang.com/peers/peer0.choray.hientang.com/tls:/etc/hyperledger/fabric/tls
      - peer0.choray.hientang.com:/var/hyperledger/production
    ports:
      - 9051:9051

  peer1.choray.hientang.com:
    container_name: peer1.choray.hientang.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.choray.hientang.com
      - CORE_PEER_ADDRESS=peer1.choray.hientang.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.choray.hientang.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.choray.hientang.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.choray.hientang.com:9051
      - CORE_PEER_LOCALMSPID=ChorayMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/choray.hientang.com/peers/peer1.choray.hientang.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/choray.hientang.com/peers/peer1.choray.hientang.com/tls:/etc/hyperledger/fabric/tls
      - peer1.choray.hientang.com:/var/hyperledger/production
    ports:
      - 10051:10051
